insert into PRODUCT  (ID, AUTHOR, DELETED, DESCRIPTION, PRICE, QUANTITY, TITLE) values (1, 'Marji', '1', 'Chocolate Bar - Oh Henry', 58, 24, 'Jimmy');
insert into PRODUCT  (ID, AUTHOR, DELETED, DESCRIPTION, PRICE, QUANTITY, TITLE) values (2, 'Adolphe', '1', 'Beer - Pilsner Urquell', 94, 72, 'Metro');
insert into PRODUCT  (ID, AUTHOR, DELETED, DESCRIPTION, PRICE, QUANTITY, TITLE) values (3, 'Pedro', '0', 'Spinach - Baby', 44, 56, 'Esprit');
insert into PRODUCT  (ID, AUTHOR, DELETED, DESCRIPTION, PRICE, QUANTITY, TITLE) values (4, 'Chrotoem', '1', 'Beans - Soya Bean', 80, 48, 'Elise');
insert into PRODUCT  (ID, AUTHOR, DELETED, DESCRIPTION, PRICE, QUANTITY, TITLE) values (5, 'Michele', '0', 'Coffee - Colombian, Portioned', 73, 65, 'GL-Class');
insert into PRODUCT   (ID, AUTHOR, DELETED, DESCRIPTION, PRICE, QUANTITY, TITLE) values (6, 'Nolana', '1', 'C - Plus, Orange', 36, 2, 'Civic');
insert into PRODUCT   (ID, AUTHOR, DELETED, DESCRIPTION, PRICE, QUANTITY, TITLE) values (7, 'Joline', '0', 'Nacho Chips', 61, 16, 'Flex');
insert into PRODUCT   (ID, AUTHOR, DELETED, DESCRIPTION, PRICE, QUANTITY, TITLE) values (8, 'Germaine', '1', 'Mushroom - Trumpet, Dry', 93, 30, 'Cherokee');
insert into PRODUCT   (ID, AUTHOR, DELETED, DESCRIPTION, PRICE, QUANTITY, TITLE) values (9, 'Sherlocke', '0', 'Piping - Bags Quizna', 68, 67, 'Tiburon');
insert into PRODUCT   (ID, AUTHOR, DELETED, DESCRIPTION, PRICE, QUANTITY, TITLE) values (10, 'Lewie', '1', 'Langers - Mango Nectar', 52, 37, 'Aura');
insert into PRODUCT   (ID, AUTHOR, DELETED, DESCRIPTION, PRICE, QUANTITY, TITLE) values (11, 'Gardy', '1', 'Wine - Stoneliegh Sauvignon', 48, 75, 'R8');